name: Trivy

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "17 4 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    name: Scan repository filesystem
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Run Trivy
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          scan-type: fs
          scanners: vuln,secret,misconfig
          format: sarif
          output: trivy-results.sarif
          exit-code: "0"
      - name: Upload SARIF artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: trivy-results
          path: trivy-results.sarif

  upload:
    name: Upload results to GitHub code scanning
    needs: scan
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Download SARIF artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: trivy-results
      - name: Upload Trivy results to GitHub code scanning
        uses: github/codeql-action/upload-sarif@eec0bff2f6c15bf3f1e8a0152f94d17664a06a06
        with:
          sarif_file: trivy-results.sarif
